baseURL = "http://chkry.github.io/"
languageCode = "en-us"
title = "Chakri Reddy"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Chakri Reddy"
    description = "Dream Design Developer"
    githubUsername = "#chkry"
    accent = "darkgrey"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift","javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:chkry@icloud.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/chkry"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/chkry"
    name = "linkedin"
    weight = 3
	
[[menu.icon]]
    url = "https://www.instagram.com/chkry"
    name = "instagram"
    weight = 4
	
[[menu.icon]]
    url = "https://www.facebook.com/chkry"
    name = "facebook"
    weight = 5
	
[[menu.icon]]
    url = "https://twitter.com/chkry/"
    name = "twitter"
    weight = 6
